name: Main
on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main
  repository_dispatch:
    types: [ periodic ]
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out the sources
        uses: actions/checkout@v3

      - name: Prepare the release notes
        uses: ForNeVeR/ChangelogAutomation.action@v1
        with:
          input: ./CHANGELOG.md
          output: ./release-notes.md
          format: Markdown
      - name: Upload the release notes
        uses: actions/upload-artifact@v4
        with:
          name: release-notes
          path: ./release-notes.md

      - name: Create the release
        if: startsWith(github.ref, 'refs/tags/v')
        id: release
        # noinspection SpellCheckingInspection
        uses: softprops/action-gh-release@v1
        with:
          body_path: ./release-notes.md
